name: Deploy with HTTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3

      - name: Запуск HTTP Server
        uses: Eun/http-server-action@v1.0.12
        with:
          directory: out
          port: 8080
          no-cache: true
          index-files: [ "index.html" ]
          allowed-methods: [ "GET", "HEAD" ]
          custom404Page: out/404/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
